# Generated by Django 5.2.18 on 2026-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=120, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Leave off for Gmail on port 587.', verbose_name='Use SSL')),
                ('smtp_username', models.CharField(blank=True, max_length=150, verbose_name='Gmail / SMTP email address')),
                ('smtp_password', models.CharField(blank=True, help_text='Gmail app password (Google Account > Security > App passwords).', max_length=150, verbose_name='App password')),
                ('sender_name', models.CharField(default='SAE India', max_length=100)),
                ('from_email', models.EmailField(blank=True, help_text='Usually the same as the SMTP email address.', max_length=254, verbose_name='From email')),
                ('notification_emails', models.TextField(blank=True, help_text='One or more email addresses, separated by commas or new lines.', verbose_name='Send enquiries to')),
                ('subject_prefix', models.CharField(default='[SAE India] ', max_length=60)),
                ('is_active', models.BooleanField(default=True, verbose_name='Send emails')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Shown in the browser tab and search results (aim for under 60 characters).', max_length=70, verbose_name='Page title')),
                ('meta_description', models.TextField(blank=True, help_text='Search result summary (aim for 150-160 characters).', max_length=300, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='Social share image')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
    ]
