# Generated by Django 5.2.18 on 2026-10-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the header from the website.', verbose_name='Show header')),
                ('site_name', models.CharField(default='SAE India', help_text='Used as the logo alt text.', max_length=120)),
                ('logo', models.ImageField(blank=True, help_text='Shown large in the sticky header; links to the top of the page.', upload_to='header/')),
            ],
            options={
                'verbose_name': 'Header & Menu',
                'verbose_name_plural': 'Header & Menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('link', models.CharField(help_text='Section anchor like #about, or a full URL.', max_length=200)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='core.headersettings')),
            ],
            options={
                'verbose_name': 'Menu item',
                'ordering': ['order', 'id'],
            },
        ),
    ]
