# Generated by Django 5.2.18 on 2026-10-08 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Hero section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='home', help_text='Menu links point here, e.g. "home" is reached with #home.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('pill_show_dot', models.BooleanField(default=True, verbose_name='Show dot before pill text')),
                ('heading_pre', models.CharField(blank=True, help_text='e.g. Auto', max_length=100, verbose_name='Heading: first part')),
                ('heading_highlight', models.CharField(blank=True, help_text='Shown in the accent colour with an underline, e.g. Performance', max_length=100, verbose_name='Heading: highlighted word')),
                ('heading_post', models.CharField(blank=True, help_text='e.g. Automotive Engineering Conference', max_length=200, verbose_name='Heading: second line')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='Show countdown')),
                ('edition_label', models.CharField(blank=True, help_text='e.g. 23RD EDITION', max_length=60)),
                ('event_datetime', models.DateTimeField(blank=True, help_text='Countdown target, in India time (IST).', null=True, verbose_name='Event date & time')),
                ('countdown_ended_text', models.CharField(default='Event started', max_length=80)),
                ('primary_button_text', models.CharField(blank=True, max_length=40)),
                ('primary_button_link', models.CharField(blank=True, help_text='Section anchor like #contact, or a full URL.', max_length=200)),
                ('show_primary_button', models.BooleanField(default=True, verbose_name='Show primary button')),
                ('secondary_button_text', models.CharField(blank=True, max_length=40)),
                ('secondary_button_link', models.CharField(blank=True, max_length=200)),
                ('show_secondary_button', models.BooleanField(default=True, verbose_name='Show secondary button')),
                ('background_image', models.ImageField(blank=True, help_text='Full-width hero background (the car and city image).', upload_to='hero/')),
                ('overlay_text', models.CharField(blank=True, help_text='Script text shown over the image, e.g. Shaping the Future of Mobility', max_length=120, verbose_name='Text on the image')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroInfoChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='event', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_chips', to='core.herosection')),
            ],
            options={
                'verbose_name': 'Info chip',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroTagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taglines', to='core.herosection')),
            ],
            options={
                'verbose_name': 'Tagline',
                'ordering': ['order', 'id'],
            },
        ),
    ]
