# Generated by Django 5.2.18 on 2026-10-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole About section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='about', help_text='Menu links point here, e.g. "about" is reached with #about.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Circular photo')),
                ('show_badge', models.BooleanField(default=True, verbose_name='Show round badge on photo')),
                ('badge_icon', models.CharField(default='directions_car', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('badge_title', models.CharField(blank=True, help_text='e.g. AUTO PERFORMANCE', max_length=80)),
                ('badge_year', models.CharField(blank=True, help_text='e.g. 2026', max_length=20)),
                ('show_button', models.BooleanField(default=True, verbose_name='Show button')),
                ('button_text', models.CharField(blank=True, max_length=40)),
                ('button_link', models.CharField(blank=True, help_text='Section anchor like #contact, or a full URL.', max_length=200)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='TopicsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Topics section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='topics', help_text='Menu links point here, e.g. "topics" is reached with #topics.', max_length=40, verbose_name='Section ID / anchor')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Small label above heading')),
                ('heading_pre', models.CharField(blank=True, max_length=150, verbose_name='Heading: first part')),
                ('heading_highlight', models.CharField(blank=True, help_text='Shown in the accent colour.', max_length=150, verbose_name='Heading: highlighted part')),
                ('subtext', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Topics Section',
                'verbose_name_plural': 'Topics Section',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='star', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('number', models.CharField(help_text='e.g. 1,000+ or 3 Days', max_length=30)),
                ('label', models.CharField(help_text='e.g. Attendees', max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.aboutsection')),
            ],
            options={
                'verbose_name': 'Stat card',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TopicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='directions_car', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='topics/', verbose_name='Card photo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.topicssection')),
            ],
            options={
                'verbose_name': 'Topic card',
                'ordering': ['order', 'id'],
            },
        ),
    ]
