# Generated by Django 5.2.18 on 2026-10-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_about_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccard',
            name='icon',
        ),
        migrations.AddField(
            model_name='topiccard',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload the round icon shown at the top-left of the card (PNG, SVG or WebP, square).', upload_to='topics/icons/', verbose_name='Icon image'),
        ),
    ]
