# Generated by Django 5.2.18 on 2026-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_topiccard_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccard',
            name='image',
            field=models.ImageField(blank=True, help_text='Background photo shown at the top-right of the card, fading out diagonally behind the icon and title.', upload_to='topics/', verbose_name='Card photo'),
        ),
    ]
