# Generated by Django 5.2.18 on 2026-10-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_topiccard_photo_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeawaysSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Key Takeaways section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='takeaways', help_text='Menu links point here, e.g. "takeaways" is reached with #takeaways.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('pill_show_dot', models.BooleanField(default=True, verbose_name='Show dot before pill text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('show_link', models.BooleanField(default=True, verbose_name='Show top-right link')),
                ('link_text', models.CharField(blank=True, max_length=60)),
                ('link_url', models.CharField(blank=True, help_text='Section anchor like #topics, or a full URL.', max_length=200)),
            ],
            options={
                'verbose_name': 'Key Takeaways Section',
                'verbose_name_plural': 'Key Takeaways Section',
            },
        ),
        migrations.CreateModel(
            name='TakeawayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='star', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('track_label', models.CharField(blank=True, help_text='Leave empty to number automatically (Track 01, Track 02...).', max_length=30)),
                ('values_label', models.CharField(default='CORE VALUES', max_length=60)),
                ('bullets', models.TextField(help_text='One bullet per line.')),
                ('link_text', models.CharField(blank=True, max_length=60, verbose_name='Action link text')),
                ('link_url', models.CharField(blank=True, help_text='Section anchor like #contact, or a full URL.', max_length=200, verbose_name='Action link URL')),
                ('accent_color', models.CharField(default='#F59E0B', help_text='Hex colour, e.g. #F59E0B', max_length=7, verbose_name='Left bar colour')),
                ('bullet_color', models.CharField(default='#059669', help_text='Hex colour, e.g. #059669', max_length=7, verbose_name='Bullet dot colour')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.takeawayssection')),
            ],
            options={
                'verbose_name': 'Takeaway card',
                'ordering': ['order', 'id'],
            },
        ),
    ]
