# Generated by Django 5.2.18 on 2026-10-08 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_takeaways'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole "What You\'ll Gain" section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='gain', help_text='Menu links point here, e.g. "gain" is reached with #gain.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('pill_show_dot', models.BooleanField(default=True, verbose_name='Show dot before pill text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('show_video', models.BooleanField(default=True, verbose_name='Show video box')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Cover image shown in the video box.', upload_to='gain/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube / Vimeo link opened when the play button is clicked.', verbose_name='Video link')),
                ('video_caption', models.CharField(blank=True, help_text='Words shown at the bottom of the video, separated by commas, e.g. Learn, Network, Grow', max_length=120)),
            ],
            options={
                'verbose_name': "What You'll Gain Section",
                'verbose_name_plural': "What You'll Gain Section",
            },
        ),
        migrations.CreateModel(
            name='GainCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='star', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.gainsection')),
            ],
            options={
                'verbose_name': 'Gain card',
                'ordering': ['order', 'id'],
            },
        ),
    ]
