# Generated by Django 5.2.18 on 2026-10-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_text', models.CharField(default='Members', max_length=80, verbose_name='Pill tag text')),
                ('pill_show_dot', models.BooleanField(default=True, verbose_name='Show dot before pill text')),
                ('title', models.CharField(help_text='e.g. Steering Committee', max_length=150)),
                ('background_image', models.ImageField(blank=True, help_text='Faint blurred photo behind this committee.', upload_to='committees/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Committee',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Include the title, e.g. Dr. G. Nagarajan', max_length=120)),
                ('designation', models.CharField(blank=True, help_text='Organisation / position line.', max_length=250)),
                ('photo', models.ImageField(blank=True, help_text='Square photo. Leave empty to show the default avatar.', upload_to='members/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove all committees from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='committee', help_text='Menu links point here, e.g. "committee" is reached with #committee.', max_length=40, verbose_name='Section ID / anchor')),
            ],
            options={
                'verbose_name': 'Committee Section',
                'verbose_name_plural': 'Committee Section',
            },
        ),
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g. Patron, SC Chair, Member', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position inside the committee. Lower numbers first.')),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.committeemember')),
            ],
            options={
                'verbose_name': 'Committee role',
                'ordering': ['committee__order', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='core.committeesection'),
        ),
    ]
