# Generated by Django 5.2.18 on 2026-10-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_committees'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Stats section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='stats', help_text='Menu links point here, e.g. "stats" is reached with #stats.', max_length=40, verbose_name='Section ID / anchor')),
                ('background_image', models.ImageField(blank=True, help_text='Blurred photo behind the stats panel.', upload_to='stats/')),
                ('hover_color', models.CharField(default='#FCD34D', help_text='Hex colour the numbers turn when hovered, e.g. #FCD34D', max_length=7, verbose_name='Number colour on hover')),
            ],
            options={
                'verbose_name': 'Stats Section',
                'verbose_name_plural': 'Stats Section',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Digits only, e.g. 2,000 (counts up on scroll).', max_length=20)),
                ('suffix', models.CharField(blank=True, default='+', help_text='Shown after the number, e.g. +', max_length=10)),
                ('label', models.CharField(help_text='e.g. VISITORS', max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.statssection')),
            ],
            options={
                'verbose_name': 'Stat',
                'ordering': ['order', 'id'],
            },
        ),
    ]
