# Generated by Django 5.2.18 on 2026-10-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seed_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Sponsorship section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='sponsors', help_text='Menu links point here, e.g. "sponsors" is reached with #sponsors.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_icon', models.CharField(blank=True, default='workspace_premium', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('show_tagline', models.BooleanField(default=True, verbose_name='Show top-right tagline')),
                ('tagline_words', models.CharField(blank=True, help_text='Words separated by commas, e.g. Partner, Grow, Lead', max_length=120)),
                ('background_image', models.ImageField(blank=True, help_text='Blurred photo behind the section.', upload_to='sponsorship/')),
            ],
            options={
                'verbose_name': 'Sponsorship Section',
                'verbose_name_plural': 'Sponsorship Section',
            },
        ),
        migrations.CreateModel(
            name='SponsorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_label', models.CharField(help_text='e.g. PLATINUM', max_length=30, verbose_name='Tier pill')),
                ('title', models.CharField(help_text='e.g. Platinum Sponsor', max_length=80, verbose_name='Package name')),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('price', models.CharField(help_text='e.g. 25,000', max_length=30)),
                ('price_unit', models.CharField(blank=True, default='/USD', max_length=20)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('benefits', models.TextField(help_text='One benefit per line.')),
                ('button_text', models.CharField(default='Get Started', max_length=40)),
                ('button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Card numbers (01, 02...) follow this.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.sponsorshipsection')),
            ],
            options={
                'verbose_name': 'Sponsor package',
                'ordering': ['order', 'id'],
            },
        ),
    ]
