# Generated by Django 5.2.18 on 2026-10-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 1. EXECUTIVE & THOUGHT LEADERSHIP PRESENCE', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Category (row group)',
                'verbose_name_plural': 'Categories (row groups)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrixSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Deliverables Matrix from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='deliverables', help_text='Menu links point here, e.g. "deliverables" is reached with #deliverables.', max_length=40, verbose_name='Section ID / anchor')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note (top-right of title bar)')),
                ('first_column_title', models.CharField(default='Deliverables & Entitlements', max_length=80)),
            ],
            options={
                'verbose_name': 'Deliverables Matrix',
                'verbose_name_plural': 'Deliverables Matrix',
            },
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Row heading, e.g. Presence at Technical Session', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first inside the category.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.matrixcategory')),
            ],
            options={
                'verbose_name': 'Matrix Row',
                'verbose_name_plural': 'Matrix Rows',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='matrixcategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.matrixsection'),
        ),
        migrations.CreateModel(
            name='MatrixTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Column heading, e.g. Platinum', max_length=60)),
                ('price', models.CharField(blank=True, help_text='e.g. ₹15,00,000', max_length=40)),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Highlight column')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (left).')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='core.matrixsection')),
            ],
            options={
                'verbose_name': 'Tier (column)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('text', 'Normal text'), ('bold', 'Bold text'), ('badge', 'Badge'), ('yes', 'Yes (green tick)'), ('dash', 'Dash'), ('na', 'Not applicable')], default='text', max_length=10)),
                ('text', models.CharField(blank=True, help_text='Leave empty for Yes / Dash / Not applicable (they show their own text).', max_length=150)),
                ('subtext', models.CharField(blank=True, help_text='e.g. 4 times a day', max_length=100, verbose_name='Small text below')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.matrixrow')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.matrixtier')),
            ],
            options={
                'verbose_name': 'Cell',
                'ordering': ['tier__order', 'id'],
            },
        ),
    ]
