# Generated by Django 5.2.18 on 2026-10-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seed_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpositionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Exposition section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='exposition', help_text='Menu links point here, e.g. "exposition" is reached with #exposition.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=150, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('show_top_button', models.BooleanField(default=True, verbose_name='Show top-right button')),
                ('top_button_text', models.CharField(blank=True, max_length=40)),
                ('top_button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
                ('venue_image', models.ImageField(blank=True, upload_to='exposition/')),
                ('venue_tag', models.CharField(blank=True, help_text='e.g. LIVE VENUE VIEW', max_length=50, verbose_name='Venue tag')),
                ('venue_title', models.CharField(blank=True, max_length=200)),
                ('venue_subtext', models.CharField(blank=True, max_length=200)),
                ('show_pass_box', models.BooleanField(default=True, verbose_name='Show pass entitlements box')),
                ('pass_title', models.CharField(blank=True, default='Exhibitor Pass Entitlements', max_length=80)),
                ('pass_tag', models.CharField(blank=True, default='Official Inclusions', max_length=40)),
                ('pass_count', models.CharField(blank=True, default='2×', help_text='Shown in the round badge', max_length=10)),
                ('pass_headline', models.CharField(blank=True, max_length=120)),
                ('pass_subline', models.CharField(blank=True, max_length=160)),
                ('pass_includes', models.CharField(blank=True, max_length=250, verbose_name='Pass includes')),
                ('pass_excludes', models.CharField(blank=True, max_length=250, verbose_name='Pass excludes')),
                ('gst_footnote', models.CharField(blank=True, max_length=120)),
                ('footer_link_text', models.CharField(blank=True, max_length=60)),
                ('footer_link_url', models.CharField(blank=True, default='#contact', max_length=200)),
            ],
            options={
                'verbose_name': 'Exposition Section',
                'verbose_name_plural': 'Exposition Section',
            },
        ),
        migrations.CreateModel(
            name='BoothSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='grid_view', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('size_label', models.CharField(help_text='e.g. 9 sq. mtr.', max_length=40)),
                ('grid_label', models.CharField(blank=True, help_text='e.g. (3 × 3)', max_length=30)),
                ('space_type', models.CharField(blank=True, default='RAW SPACE', max_length=30)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 3m × 3m', max_length=30)),
                ('category', models.CharField(blank=True, help_text='e.g. STARTUP & SPECIALIST', max_length=80)),
                ('name', models.CharField(help_text='e.g. Standard Turnkey', max_length=80)),
                ('price_label', models.CharField(blank=True, default='VALUE IN INR *', max_length=40)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('price', models.CharField(help_text='e.g. 1,50,000', max_length=30)),
                ('gst_note', models.CharField(blank=True, default='*18% GST applicable extra', max_length=80)),
                ('button_text', models.CharField(default='BOOK SPACE', max_length=40)),
                ('button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
                ('button_style', models.CharField(choices=[('outline', 'Outline'), ('dark', 'Dark'), ('accent', 'Accent colour')], default='outline', max_length=10)),
                ('tint_color', models.CharField(default='#F0FDFA', max_length=7, verbose_name='Card tint colour')),
                ('accent_color', models.CharField(default='#0D9488', help_text='Used for the size block, the flagship border and "Accent" buttons.', max_length=7, verbose_name='Accent colour')),
                ('flagship_tag', models.CharField(blank=True, help_text='e.g. FLAGSHIP OPTION. Fill this to give the card the highlighted look.', max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='core.expositionsection')),
            ],
            options={
                'verbose_name': 'Booth space',
                'ordering': ['order', 'id'],
            },
        ),
    ]
