# Generated by Django 5.2.18 on 2026-10-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seed_exposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSponsorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Special Event Sponsorships section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='special-sponsorships', help_text='Menu links point here, e.g. "special-sponsorships" is reached with #special-sponsorships.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('show_tag', models.BooleanField(default=True, verbose_name='Show top-right tag')),
                ('tag_text', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Special Event Sponsorships',
                'verbose_name_plural': 'Special Event Sponsorships',
            },
        ),
        migrations.CreateModel(
            name='SpecialSponsorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_text', models.CharField(help_text='e.g. NETWORKING BREAKS', max_length=40, verbose_name='Side strip text')),
                ('strip_color', models.CharField(default='#0D9488', max_length=7, verbose_name='Side strip / accent colour')),
                ('exclusive_tag', models.CharField(blank=True, help_text='e.g. EXCLUSIVE. Leave empty for none.', max_length=30)),
                ('slot_tag', models.CharField(blank=True, default='Slot Available', help_text='Leave empty to hide.', max_length=30)),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Highlight card (coloured border)')),
                ('name', models.CharField(help_text='e.g. Hi-Tea Sponsor', max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('price_label', models.CharField(blank=True, default='INVESTMENT', max_length=30)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('price', models.CharField(help_text='e.g. 3,00,000', max_length=30)),
                ('price_note_prefix', models.CharField(blank=True, default='INR', help_text='Shows as "(INR 3,00,000)" under the price. Leave empty to hide.', max_length=10, verbose_name='Small price note prefix')),
                ('deliverables_label', models.CharField(blank=True, default='DELIVERABLES & ENTITLEMENTS', max_length=60)),
                ('deliverables', models.TextField(blank=True, help_text='One item per line.')),
                ('passes_label', models.CharField(blank=True, default='Complimentary Passes:', max_length=40)),
                ('passes_value', models.CharField(blank=True, help_text='e.g. 1 Delegate', max_length=40)),
                ('button_text', models.CharField(default='EXPRESS INTEREST', max_length=40)),
                ('button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
                ('button_style', models.CharField(choices=[('outline', 'Outline'), ('dark', 'Dark'), ('accent', 'Accent colour')], default='outline', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.specialsponsorsection')),
            ],
            options={
                'verbose_name': 'Sponsorship card',
                'ordering': ['order', 'id'],
            },
        ),
    ]
