# Generated by Django 5.2.18 on 2026-10-08 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seed_special_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Business Meeting Room section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='meeting-room', help_text='Menu links point here, e.g. "meeting-room" is reached with #meeting-room.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=80, verbose_name='Pill tag text')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('currency_label', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('price', models.CharField(blank=True, help_text='e.g. 5,000', max_length=30)),
                ('price_unit', models.CharField(blank=True, default='/ hour', max_length=20)),
                ('gst_note', models.CharField(blank=True, max_length=120)),
                ('button_text', models.CharField(blank=True, max_length=40)),
                ('button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
            ],
            options={
                'verbose_name': 'Business Meeting Room',
                'verbose_name_plural': 'Business Meeting Room',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='star', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.meetingroomsection')),
            ],
            options={
                'verbose_name': 'Feature card',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='sell', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('label', models.CharField(help_text='Bold part, e.g. Booking Fee:', max_length=60)),
                ('text', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.meetingroomsection')),
            ],
            options={
                'verbose_name': 'Detail line',
                'ordering': ['order', 'id'],
            },
        ),
    ]
