# Generated by Django 5.2.18 on 2026-10-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_meeting_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expositionsection',
            options={'verbose_name': 'Sponsorship: Exposition', 'verbose_name_plural': 'Sponsorship: Exposition'},
        ),
        migrations.AlterModelOptions(
            name='matrixrow',
            options={'ordering': ['category__order', 'order', 'id'], 'verbose_name': 'Sponsorship: Matrix Row', 'verbose_name_plural': 'Sponsorship: Matrix Rows'},
        ),
        migrations.AlterModelOptions(
            name='matrixsection',
            options={'verbose_name': 'Sponsorship: Deliverables Matrix', 'verbose_name_plural': 'Sponsorship: Deliverables Matrix'},
        ),
        migrations.AlterModelOptions(
            name='specialsponsorsection',
            options={'verbose_name': 'Sponsorship: Special Events', 'verbose_name_plural': 'Sponsorship: Special Events'},
        ),
        migrations.AlterModelOptions(
            name='sponsorshipsection',
            options={'verbose_name': 'Sponsorship: Packages', 'verbose_name_plural': 'Sponsorship: Packages'},
        ),
    ]
