# Generated by Django 5.2.18 on 2026-10-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sponsorship_menu_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechHiveSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Startup & Delegate Packages section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='techhive', help_text='Menu links point here, e.g. "techhive" is reached with #techhive.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('show_top_button', models.BooleanField(default=True, verbose_name='Show top-right button')),
                ('top_button_text', models.CharField(blank=True, max_length=40)),
                ('top_button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
                ('show_panel', models.BooleanField(default=True, verbose_name='Show TechHive panel')),
                ('panel_tag1', models.CharField(blank=True, max_length=50, verbose_name='Tag 1')),
                ('panel_tag2', models.CharField(blank=True, max_length=50, verbose_name='Tag 2')),
                ('panel_title', models.CharField(blank=True, max_length=100)),
                ('panel_description', models.CharField(blank=True, max_length=250)),
                ('fee_label', models.CharField(blank=True, default='REGISTRATION FEE', max_length=40)),
                ('fee_tag', models.CharField(blank=True, default='All Inclusives', max_length=40)),
                ('fee_currency', models.CharField(default='INR', max_length=10)),
                ('fee_price', models.CharField(blank=True, help_text='e.g. 50,000', max_length=30)),
                ('fee_unit', models.CharField(blank=True, default='/ registration', max_length=30)),
                ('fee_gst_note', models.CharField(blank=True, max_length=120)),
                ('deliverables_label', models.CharField(blank=True, default='STARTUP DELIVERABLES & ENTITLEMENTS', max_length=80)),
                ('apply_button_text', models.CharField(blank=True, max_length=60)),
                ('apply_button_link', models.CharField(blank=True, default='#contact', max_length=200)),
                ('show_delegate_matrix', models.BooleanField(default=True, verbose_name='Show delegate investment matrix')),
                ('matrix_title', models.CharField(blank=True, max_length=100)),
                ('matrix_subtitle', models.CharField(blank=True, max_length=150)),
                ('matrix_badge', models.CharField(blank=True, help_text='e.g. Early Bird Active till Sep 15, 2026. Leave empty to hide.', max_length=80, verbose_name='Top-right badge')),
                ('category_column_title', models.CharField(default='Category', max_length=40)),
                ('category_column_note', models.CharField(blank=True, default='(All Nations)', max_length=40)),
                ('early_column_title', models.CharField(blank=True, max_length=60)),
                ('early_column_note', models.CharField(blank=True, default='EARLY BIRD', max_length=40)),
                ('standard_column_title', models.CharField(blank=True, max_length=60)),
                ('standard_column_note', models.CharField(blank=True, default='Standard Tariff', max_length=40)),
                ('matrix_gst_note', models.CharField(blank=True, max_length=150)),
                ('matrix_button_text', models.CharField(blank=True, max_length=40)),
                ('matrix_button_link', models.CharField(blank=True, default='#contact', max_length=200)),
            ],
            options={
                'verbose_name': 'Startup & Delegate Packages',
                'verbose_name_plural': 'Startup & Delegate Packages',
            },
        ),
        migrations.CreateModel(
            name='TechHiveDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='person', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('subline', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.techhivesection')),
            ],
            options={
                'verbose_name': 'Deliverable',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DelegateRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. SAEINDIA Member', max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, help_text='Green note under the category, e.g. Save ₹2,500 with membership', max_length=100)),
                ('early_price', models.CharField(help_text='e.g. ₹15,000', max_length=30)),
                ('standard_price', models.CharField(help_text='e.g. ₹17,500', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.techhivesection')),
            ],
            options={
                'verbose_name': 'Delegate rate',
                'ordering': ['order', 'id'],
            },
        ),
    ]
