# Generated by Django 5.2.18 on 2026-10-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_techhive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Event Gallery from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='gallery', help_text='Menu links point here, e.g. "gallery" is reached with #gallery.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=80, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('subtext', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Event Gallery',
                'verbose_name_plural': 'Event Gallery',
            },
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Sponsors & Partners section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='partners', help_text='Menu links point here, e.g. "partners" is reached with #partners.', max_length=40, verbose_name='Section ID / anchor')),
                ('pill_text', models.CharField(blank=True, max_length=80, verbose_name='Pill tag text')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('autoplay', models.BooleanField(default=True, verbose_name='Autoplay (scrolls by itself, pauses on hover)')),
                ('speed_seconds', models.PositiveSmallIntegerField(default=30, help_text='Higher number = slower scroll.', verbose_name='Scroll speed (seconds per loop)')),
                ('show_arrows', models.BooleanField(default=True, verbose_name='Show left / right arrows')),
            ],
            options={
                'verbose_name': 'Sponsors & Partners',
                'verbose_name_plural': 'Sponsors & Partners',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Also used as the image description (alt text).', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallerysection')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name (also used as the logo description).', max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True, help_text='Optional: opens in a new tab when the logo is clicked.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='core.partnerssection')),
            ],
            options={
                'verbose_name': 'Logo',
                'ordering': ['order', 'id'],
            },
        ),
    ]
