# Generated by Django 5.2.18 on 2026-10-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_seed_gallery_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Registration Banner from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='register', help_text='Menu links point here, e.g. "register" is reached with #register.', max_length=40, verbose_name='Section ID / anchor')),
                ('background_image', models.ImageField(blank=True, upload_to='banner/')),
                ('pill_text', models.CharField(blank=True, max_length=120, verbose_name='Pill tag text')),
                ('heading_line1', models.CharField(blank=True, max_length=150, verbose_name='Heading: first line (italic)')),
                ('heading_line2', models.CharField(blank=True, max_length=100, verbose_name='Heading: second line (accent colour)')),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=40)),
                ('button_link', models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200)),
            ],
            options={
                'verbose_name': 'Registration Banner',
                'verbose_name_plural': 'Registration Banner',
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='event', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('text', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bannersection')),
            ],
            options={
                'verbose_name': 'Banner item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BannerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='info', help_text='Enter a Google Material Symbols icon name (e.g. bolt, cloud, headset_mic). Browse available names at fonts.google.com/icons', max_length=60)),
                ('label', models.CharField(help_text='Small capital label, e.g. CONFERENCE VENUE', max_length=80)),
                ('value', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cells', to='core.bannersection')),
            ],
            options={
                'verbose_name': 'Info strip cell',
                'ordering': ['order', 'id'],
            },
        ),
    ]
