# Generated by Django 5.2.18 on 2026-10-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_seed_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Contact section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='contact', help_text='Menu links point here, e.g. "contact" is reached with #contact.', max_length=40, verbose_name='Section ID / anchor')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Small label above heading')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('side_text', models.CharField(blank=True, max_length=200, verbose_name='Line on the right of the heading')),
                ('show_qr', models.BooleanField(default=True, verbose_name='Show QR card')),
                ('qr_pill_text', models.CharField(blank=True, max_length=60)),
                ('qr_title', models.CharField(blank=True, max_length=80)),
                ('qr_subtext', models.CharField(blank=True, max_length=200)),
                ('qr_image', models.ImageField(blank=True, upload_to='contact/', verbose_name='QR code image')),
                ('qr_caption', models.CharField(blank=True, max_length=60)),
                ('show_strip', models.BooleanField(default=True, verbose_name='Show bottom strip')),
                ('strip_label', models.CharField(blank=True, max_length=120)),
                ('strip_link_text', models.CharField(blank=True, max_length=150)),
                ('strip_link_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='e.g. SECRETARIAT', max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('phones', models.TextField(blank=True, help_text='One phone number per line (you can add more than one).')),
                ('emails', models.TextField(blank=True, help_text='One email address per line (you can add more than one).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.contactsection')),
            ],
            options={
                'verbose_name': 'Contact person',
                'verbose_name_plural': 'Contact people',
                'ordering': ['order', 'id'],
            },
        ),
    ]
