# Generated by Django 5.2.18 on 2026-10-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_seed_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the whole Desk Coordinators section from the live site.', verbose_name='Show this section on the website')),
                ('menu_anchor', models.SlugField(default='coordinators', help_text='Menu links point here, e.g. "coordinators" is reached with #coordinators.', max_length=40, verbose_name='Section ID / anchor')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='Small label above heading')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('side_text', models.CharField(blank=True, max_length=200, verbose_name='Line on the right of the heading')),
                ('desk_background_image', models.ImageField(blank=True, upload_to='coordinators/', verbose_name='Background photo for the dark desk cards')),
            ],
            options={
                'verbose_name': 'Desk Coordinators',
                'verbose_name_plural': 'Desk Coordinators',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phones', models.TextField(blank=True, help_text='One phone number per line (you can add more than one).')),
                ('emails', models.TextField(blank=True, help_text='One email address per line (you can add more than one).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='core.coordinatorssection')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='e.g. EXPOSITION DESK', max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('phones', models.TextField(blank=True, help_text='One phone number per line (you can add more than one).')),
                ('emails', models.TextField(blank=True, help_text='One email address per line (you can add more than one).')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='core.coordinatorssection')),
            ],
            options={
                'verbose_name': 'Desk card',
                'ordering': ['order', 'id'],
            },
        ),
    ]
