# Generated by Django 5.2.18 on 2026-10-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seed_coordinators'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove the footer from the website.', verbose_name='Show footer')),
                ('logo', models.ImageField(blank=True, upload_to='footer/', verbose_name='Footer logo (white version)')),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('show_website_pill', models.BooleanField(default=True, verbose_name='Show website pill')),
                ('website_text', models.CharField(blank=True, help_text='e.g. saeindia.org/apac23', max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('link', models.CharField(help_text='Section anchor like #about, or a full URL.', max_length=200)),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Highlight (accent colour)')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersection')),
            ],
            options={
                'verbose_name': 'Footer link',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('link', models.CharField(blank=True, help_text='Section anchor or full URL. Leave empty until the page / popup / document is ready.', max_length=200)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_links', to='core.footersection')),
            ],
            options={
                'verbose_name': 'Legal link',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('x', 'X (Twitter)'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(blank=True, help_text='Full link to the profile or page. Inactive or empty links are hidden.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='core.footersection')),
            ],
            options={
                'verbose_name': 'Social media link',
                'ordering': ['order', 'id'],
            },
        ),
    ]
