# Generated by Django 5.2.18 on 2026-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_seed_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Designed & Developed by Vetri IT Systems', help_text='The whole line is shown as a link in the footer.', max_length=150)),
                ('url', models.URLField(default='https://vetriitsystems.com/', verbose_name='Link')),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Show credits line')),
            ],
            options={
                'verbose_name': 'Credits',
                'verbose_name_plural': 'Credits',
            },
        ),
    ]
