# Generated by Django 5.2.18 on 2026-10-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersection',
            name='logo',
        ),
    ]
