# Generated by Django 5.2.18 on 2026-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_seed_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='button_link',
            field=models.CharField(blank=True, default='#contact', help_text='Section anchor like #contact, or a full URL.', max_length=200),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open button link in a new tab'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text',
            field=models.CharField(blank=True, default='Register Now', max_length=40),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='show_button',
            field=models.BooleanField(default=True, verbose_name='Show header button'),
        ),
    ]
