# Generated by Django 5.2.18 on 2026-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_header_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='qr_background_image',
            field=models.ImageField(blank=True, help_text='Faint photo behind the dark QR card.', upload_to='contact/', verbose_name='QR card background photo'),
        ),
    ]
