# Generated by Django 5.2.18 on 2026-10-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_qr_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to remove both floating buttons from the website.', verbose_name='Show floating buttons')),
                ('show_whatsapp', models.BooleanField(default=True, verbose_name='Show WhatsApp button')),
                ('whatsapp_number', models.CharField(default='+91 8870471511', help_text='With country code, e.g. +91 8870471511', max_length=30)),
                ('whatsapp_message', models.CharField(blank=True, default='Hello! I would like to know more about APAC 23.', help_text='Text already typed in when the chat opens. Leave empty for none.', max_length=250)),
                ('show_call', models.BooleanField(default=True, verbose_name='Show Call button')),
                ('call_number', models.CharField(default='+91 8870471511', help_text='With country code, e.g. +91 8870471511', max_length=30)),
            ],
            options={
                'verbose_name': 'Floating Buttons',
                'verbose_name_plural': 'Floating Buttons',
            },
        ),
    ]
