# Generated by Django 5.2.18 on 2026-10-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_seed_floating_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderButtonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Register as Author', max_length=60)),
                ('link', models.CharField(help_text='Full web address or a section anchor like #contact.', max_length=300)),
                ('open_in_new_tab', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_options', to='core.headersettings')),
            ],
            options={
                'verbose_name': 'Header button choice',
                'ordering': ['order', 'id'],
            },
        ),
    ]
