# Generated by Django 5.2.18 on 2026-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_footer_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Short name used in the link, e.g. "terms". The popup opens from a link to #legal-terms.', max_length=40, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.TextField(blank=True, help_text='Lines shown under the title (one per line), e.g. the event name and dates.')),
                ('content', models.TextField(help_text='Type the text. Start a heading line with ## (for example: ## 1. Registration). Start a bullet line with a dash and a space (- like this). Leave a blank line between paragraphs.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this page')),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages (popups)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
