# Generated by Django 5.2.18 on 2026-10-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_seed_legal_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Shown under the code, e.g. Author registration', max_length=60)),
                ('image', models.ImageField(upload_to='contact/')),
                ('link', models.URLField(blank=True, help_text='Optional: opens in a new tab when the QR code is clicked or tapped.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False, help_text='Soft delete: hidden on the site.', verbose_name='Deleted')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='core.contactsection')),
            ],
            options={
                'verbose_name': 'QR code',
                'ordering': ['order', 'id'],
            },
        ),
    ]
