# Generated by Django 5.2.18 on 2026-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_special_event_buttons_consistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='use_register_dropdown',
            field=models.BooleanField(default=False, help_text='Tick to show the Author / Delegate choices (set in Header & Menu) instead of the link above.', verbose_name='Open the Register Now choices'),
        ),
    ]
